language: java
jdk:
- oraclejdk8
- oraclejdk9
- openjdk8
addons:
  apt:
    packages:
    - nodejs
services:
- docker
before_install:
- docker network create dvs
- export NETWORK_INTERFACE_NAME=$(route | grep '^default' | grep -o '[^ ]*$')
- export NETWORK_INTERFACE_ADDRESS=$(ip addr show $NETWORK_INTERFACE_NAME | grep -Po 'inet \K[\d.]+')
- docker-compose -f compose/deps/docker-compose.yml up
- sleep 480
- docker ps -a
- npm install newman --global;
install:
- ./gradlew assemble
script:
- ./gradlew check
- ./gradlew bootRun &
- sleep 45
- curl http://localhost:5635/health
- cd $TRAVIS_BUILD_DIR/src/test/resources && newman run AssetAPI.postman_collection.json -e AeselTest.postman_environment.json
after_failure:
- cd $TRAVIS_BUILD_DIR && cat logs/avc.log | grep ERROR
