language: java
jdk:
- oraclejdk8
addons:
  apt:
    packages:
    - nodejs
services:
- docker
before_install:
- docker network create dvs
- export NETWORK_INTERFACE_NAME=$(route | grep '^default' | grep -o '[^ ]*$')
- export NETWORK_INTERFACE_ADDRESS=$(ip addr show $NETWORK_INTERFACE_NAME | grep -Po 'inet \K[\d.]+')
- docker-compose -f compose/deps/docker-compose.yml up &
- sleep 480
- docker ps -a
- npm install newman --global;
install:
- ./gradlew assemble
script:
- ./gradlew check
- ./gradlew bootRun &
- sleep 45
- curl http://localhost:5635/health
- cd $TRAVIS_BUILD_DIR/src/test/resources && newman run AssetAPI.postman_collection.json -e AeselTest.postman_environment.json
- docker stop $(docker ps -aq)
- docker rm $(docker ps -aq)
after_success:
  - cd $TRAVIS_BUILD_DIR && docker build -t aostreetart/kelona:latest .
  - cd $TRAVIS_BUILD_DIR && scripts/linux/push_docker.sh $DOCKER_MAIL $DOCKER_UN $DOCKER_PW $TRAVIS_BRANCH
after_failure:
- cd $TRAVIS_BUILD_DIR && cat logs/avc.log | grep ERROR
notifications:
  slack:
    secure: YGqapA0ZH4TFv9G0otZRcqQXTpL0Y/4J51V0pm6mNp9bQi9XIoE8zoCEtZcCPnEFWjPoq8Nj1tA86WzRnriOzZIkzm83Ou/ZRcB4ZCmro0qC9fffALubzEvbqqG3TW77Xq3N7orz7Bjs8H2nxYgNQPjfQtaIMqL8ziGvf6s22LBQOBlusFJF3uELhtFCXvToKTO6XkkmLQ7Oj/qeX/kF6k7R1+lLna4JVNgkIpoEoubticMqY+/3MiS1tY41Y9phW3rxOi1O4upWnRo0fR/1fXS6Gn2Tr2PBSxdNzaJsbhJWUHf+e4DJtPkuqc7ftqSrb4DZhSukBnjXpMtE45oYcWo3h4txxTGnnzD9yMnEHegvlj1kQbcwCNc8We3RDAP80DWgvH3i1rghJ01n0okOQ4Zokz0Ntw+8pExFXO7qfa1vH3s36oIOF97cU+HWGGxqDmcBNVLNBvYfEWqWEOpZeP5p6YvnOCBwSoPXvjbcu+PeP1n9b+95ZBTTzoTJ5sHy54q7r8o/037n5kij3BfKJIjgVHkFPpXVMWkSsMZnQpBHe0RF+Iiv9SIcySF1ln3jUWIBM4heXYywYNjE6Qpw0xVQ3oq4xBPxmcSN+kcWC7wiwMGLzBQErNhbI2IRNVRAZCWIpGVnrHXB4Ev6+A2YgH4c3pWZsXmXu3L1esLv0ac=
