version: '2.1'

services:
  mongo:
    image: mongo
    container_name: document-db
    restart: always
    ports:
      - "27017:27017"
  kelona:
    image: aostreetart/kelona:latest
    container_name: kelona
    ports:
      - "5635:5635"
    depends_on:
      registry:
        condition: service_healthy
    environment:
      - MONGO_HOSTS=document-db
      - SPRING_CLOUD_CONSUL_HOST=registry
      - SPRING_CLOUD_CONSUL_DISCOVERY_PREFERIPADDRESS=true
